name: Insta Fetch if Missing Digimon Cards
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-cards-if-missing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Check for card_data Folder and Run Script if Missing
        run: |
          if [ ! -d "card_data" ]; then
            echo "card_data folder does not exist. Running script..."
            chmod +x ./scripts/fetch_cards.sh
            ./scripts/fetch_cards.sh
          else
            echo "card_data folder exists. No action needed."
          fi

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          if [ "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update card data from fetch_cards script"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
